version: '3.4'

services:
  frontend:
    image: frontend
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
